add command runner workflow
open-web3-stack/polkadot-ecosystem-tests pull request #44
Opened 2024-09-12 03:57 UTC by ntduan

fix issue #2

2024-09-13 05:06 UTC, xlc requested changes
can we have most of the JS code in .js file and only load from .js file in yml file? it will be easier to read & test

2024-09-13 05:06 UTC, xlc commented on .github/workflows/command-runner.yml
> +              ref: currentBranch
we need to make sure we always fetch from this repo (not fork) and using master (not a branch)
otherwise others can fork and modify the config to gain access

2024-09-13 05:06 UTC, xlc commented on .github/workflows/command-runner.yml
> +            echo "::set-output name=changes_detected::false"
I think this is the old deprecated syntax, should use the new one

2024-09-14 07:50 UTC, ntduan commented
> can we have most of the JS code in .js file and only load from .js file in yml file? it will be easier to read & test

fixed

2024-09-16 00:04 UTC, xlc commented on .github/workflows/command-runner.yml
> +            console.log(context)
```suggestion
```

2024-09-16 00:04 UTC, merged